name: Run npx standard

on:
  push:
    paths:
      - '**.js'

jobs:
  npx-standard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run flow
        run: npm run flow
