name: Run npx standard

on:
  push:
    paths:
      - '**.js'

jobs:
  npx-standard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35.7.6
          
      - name: Run npx standard
        run: npx standard ${ steps.changed-files.outputs.all_changed_files }
